language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install $(cat requirements/system/ubuntu/apt-packages.txt)
    - git submodule update --init --recursive
    - bundle install
install:
    - rake install_prereqs
script: scripts/travis.sh
