language: python
python:
    - "2.7"
before_install:
    - "sudo apt-get install
       gfortran
       libatlas-dev
       libblas-dev
       liblapack-dev
       liblapack3gf
       libfreetype6-dev
       libpng12-dev
       libjpeg-dev
       libxml2-dev
       libxslt-dev
       yui-compressor
       graphviz
       libgraphviz-dev
       graphviz-dev
       mysql-server
       libmysqlclient-dev
       libgeos-dev
       libreadline6
       libreadline6-dev
       python-numpy
       python-scipy"
    - ln -s /usr/lib/python2.7/dist-packages/scipy* $VIRTUAL_ENV/lib/python*/site-packages
    - git submodule update --init --recursive
    - bundle install
install:
    - rake install_prereqs
script: scripts/travis.sh
virtualenv:
    system_site_packages: true
services:
    - mongodb
